
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crkvena_Kancelarija.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Dokument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokument()
        {
            this.Krstenicas = new HashSet<Krstenica>();
            this.Narudzbenicas = new HashSet<Narudzbenica>();
            this.Umrlicas = new HashSet<Umrlica>();
            this.VencaniLists = new HashSet<VencaniList>();
        }

        CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();

        public int SifraDokumenta { get; set; }
        public string VrstaDokumenta { get; set; }
        public static IEnumerable<Dokument> GetDok()
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();
            List<Dokument> dokumenti = new List<Dokument>();

            foreach (Dokument d in cr.Dokuments)
            {
                Dokument dokumentiBO = new Dokument();

                dokumentiBO.SifraDokumenta = d.SifraDokumenta;

                dokumentiBO.VrstaDokumenta = d.VrstaDokumenta;

                dokumenti.Add(dokumentiBO);
            }
            return dokumenti;
        }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Krstenica> Krstenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbenica> Narudzbenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umrlica> Umrlicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VencaniList> VencaniLists { get; set; }
    }
}





