

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crkvena_Kancelarija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int ID { get; set; }
        [DisplayName("Корисничко име")]
        [Required(ErrorMessage = "Морате попунити поље корисник.")]
        public string Korisnik { get; set; }
        [DisplayName("Шифра")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Морате попунити поље шифра.")]
        public string Sifra { get; set; }

        public string LoginErrorPoruka { get; set; }
        [DisplayName("Е-пошта")]
        [Required(ErrorMessage = "Морате попунити поље e-пошта.")]
        public string Email { get; set; }

        public string TipKorisnika { get; set; }
        [DisplayName("Телефон")]
        [Required(ErrorMessage = "Морате попунити поље телефон.")]
        public string Telefon { get; set; }
        [DisplayName("Име")]
        [Required(ErrorMessage = "Морате попунити поље име.")]
        public string Ime { get; set; }
        [DisplayName("Презиме")]
        [Required(ErrorMessage = "Морате попунити поље презиме.")]
        public string Prezime { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbenica> Narudzbenicas { get; set; }
    }
}





