


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crkvena_Kancelarija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Narudzbenica
    {
        public int SifraNarudzbenice { get; set; }
        [DisplayName("Врста документа")]
        [Required(ErrorMessage = "Морате попунити поље документ.")]
        public int SifraDokumenta { get; set; }
        [DisplayName("Име")]
        [Required(ErrorMessage = "Морате попунити поље име.")]
        public string Ime { get; set; }
        [DisplayName("Презиме")]
        [Required(ErrorMessage = "Морате попунити поље презиме.")]
        public string Prezime { get; set; }
        [DisplayName("Храм")]
        [Required(ErrorMessage = "Морате попунити поље храм.")]
        public string Hram { get; set; }
        [DisplayName("Телефон")]
        [Required(ErrorMessage = "Морате попунити поље телефон.")]
        public string Telefon { get; set; }
        [DisplayName("Е-пошта")]
        [Required(ErrorMessage = "Морате попунити поље е-пошта.")]
        public string Email { get; set; }
        [DisplayName("Датум")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Datum { get; set; }
        [DisplayName("Послао(ИД)")]
        public int ID { set; get; }
        [DisplayName("Решено")]
        public Nullable<bool> Reseno { get; set; }
    
        public virtual Dokument Dokument { get; set; }
        public virtual Login Login { get; set; }


        public static IEnumerable<Narudzbenica> listaMolbi()
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();
            List<Narudzbenica> narudzbenice = new List<Narudzbenica>();

            foreach (Narudzbenica k in cr.Narudzbenicas)
            {
                Narudzbenica narudzbenicaBO = new Narudzbenica();

                narudzbenicaBO.Dokument = new Dokument()
                {

                    VrstaDokumenta = k.Dokument.VrstaDokumenta,
                };

                narudzbenicaBO.ID = k.Login.ID;

                narudzbenicaBO.Ime = k.Ime;

                narudzbenicaBO.Prezime = k.Prezime;

                narudzbenicaBO.SifraNarudzbenice = k.SifraNarudzbenice;

                narudzbenicaBO.Hram = k.Hram;

                narudzbenicaBO.Datum = k.Datum;

                narudzbenicaBO.Telefon = k.Telefon;

                narudzbenicaBO.Email = k.Email;

                narudzbenicaBO.Reseno = k.Reseno;

                narudzbenice.Add(narudzbenicaBO);
            }
            return narudzbenice;
        }


        public static IEnumerable<Narudzbenica> GetByDate(DateTime start, DateTime end)
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();
            List<Narudzbenica> narudzbenica = new List<Narudzbenica>();

            foreach (Narudzbenica k in cr.Narudzbenicas.Where(t => t.Datum >= start && t.Datum <= end))
            {
                Narudzbenica narudzbenicaBO = new Narudzbenica();

                narudzbenicaBO.Dokument = new Dokument()
                {
                    VrstaDokumenta = k.Dokument.VrstaDokumenta,
                };
                narudzbenicaBO.ID = k.Login.ID;


                narudzbenicaBO.Ime = k.Ime;

                narudzbenicaBO.Prezime = k.Prezime;

                narudzbenicaBO.Hram = k.Hram;

                narudzbenicaBO.Email = k.Email;

                narudzbenicaBO.Telefon = k.Telefon;

                narudzbenicaBO.Datum = k.Datum;

                narudzbenicaBO.Reseno = k.Reseno;

                narudzbenica.Add(narudzbenicaBO);
            }
            return narudzbenica;
        }
    }
}






   
