

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crkvena_Kancelarija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Umrlica
    {
        [DisplayName("Шифра документа")]
        [Required(ErrorMessage = "Морате унети шифру 2")]
        public int SifraDokumenta { get; set; }
        [DisplayName("Шифра умрлице")]
        [Required(ErrorMessage = "Морате унети шифру умрлице")]
        public int SifraUmrlice { get; set; }
        [DisplayName("Име")]
        [Required(ErrorMessage = "Морате унети име преминулог")]
        public string ImePreminulog { get; set; }
        [DisplayName("Презиме")]
        [Required(ErrorMessage = "Морате унети презиме преминулог")]
        public string PrezimePreminulog { get; set; }
        [DisplayName("Пол")]
        public string Pol { get; set; }
        [DisplayName("Датум рођења")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Морате унети датум рођења")]
        public System.DateTime DatumRodjenja { get; set; }
        [DisplayName("Место рођења")]
        [Required(ErrorMessage = "Морате унети место рођења")]
        public string MestoRodjenja { get; set; }
        [DisplayName("Епархија")]
        [Required(ErrorMessage = "Морате унети епархију")]
        public string Eparhija { get; set; }
        [DisplayName("Храм")]
        [Required(ErrorMessage = "Морате унети храм")]
        public string Hram { get; set; }
        [DisplayName("Текућа година")]
        [Required(ErrorMessage = "Морате унети текућу годину")]
        public int TekucaGodina { get; set; }
        [DisplayName("Занимање преминулог")]
        [Required(ErrorMessage = "Морате унети занимање преминулог")]
        public string ZanimanjePreminulog { get; set; }
        [DisplayName("Место рођења преминулог")]
        [Required(ErrorMessage = "Морате унети место рођења")]
        public string MestoRodjenjaPreminulog { get; set; }
        [DisplayName("Брачно стање")]
        [Required(ErrorMessage = "Морате унети брачно стање")]
        public string BracnoStanje { get; set; }
        [DisplayName("Име мужа/жене")]

        public string ImeBracnogPartnera { get; set; }
        [DisplayName("Презиме мужа/жене")]

        public string PrezimeBracnogPartnera { get; set; }
        [DisplayName("Занимање мужа/жене")]

        public string ZanimanjeBracnogPartnera { get; set; }
        [DisplayName("Место становања мужа/жене")]

        public string MestoStanovanjaBracnogPartnera { get; set; }
        [DisplayName("Број деце")]
        [Required(ErrorMessage = "Морате унети број деце")]
        public Nullable<int> BrojDece { get; set; }
        [DisplayName("Подаци о деци")]

        [DataType(DataType.MultilineText)]
        public string PodaciODeci { get; set; }
        [DisplayName("Место преминућа")]
        [Required(ErrorMessage = "Морате унети место преминућа")]
        public string MestoPreminuca { get; set; }
        [DisplayName("Датум смрти")]
        [Required(ErrorMessage = "Морате унети датум смрти")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumSmrti { get; set; }
        [DisplayName("Датум сахране")]
        [Required(ErrorMessage = "Морате унети датум сахране")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumSahrane { get; set; }
        [DisplayName("Место и гробље")]
        [Required(ErrorMessage = "Морате унети место и гробље")]
        public string MestoIGrobljeSahrane { get; set; }
        [DisplayName("Узрок смрти")]
        [Required(ErrorMessage = "Морате унети узрок смрти")]
        public string UzrokSmrti { get; set; }
        [DisplayName("Име свештеника")]
        [Required(ErrorMessage = "Морате унети име свештеника")]
        public string ImeSvestenika { get; set; }
        [DisplayName("Презиме свештеника")]
        [Required(ErrorMessage = "Морате унети презиме свештеника")]
        public string PrezimeSvestenika { get; set; }
        [DisplayName("Исповеђен и причешћен")]
        [Required(ErrorMessage = "Исповеђен и причешћен?")]
        public string IspovedjenIPricescen { get; set; }
        [DisplayName("Примедба")]
        [DataType(DataType.MultilineText)]
        public string Primedba { get; set; }


        public virtual Dokument Dokument { get; set; }


        public static IEnumerable<Umrlica> GetBySifraUm(int Sifra)
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();

            List<Umrlica> umrlice = new List<Umrlica>();

            foreach (Umrlica u in cr.Umrlicas.Where(t => t.SifraDokumenta == Sifra))
            {
                Umrlica umrlicaBO = new Umrlica();

                umrlicaBO.Dokument = new Dokument()
                {
                    SifraDokumenta = u.Dokument.SifraDokumenta,
                };

                umrlicaBO.SifraUmrlice = u.SifraUmrlice;

                umrlicaBO.ImePreminulog = u.ImePreminulog;

                umrlicaBO.PrezimePreminulog = u.PrezimePreminulog;

                umrlicaBO.Pol = u.Pol;

                umrlicaBO.DatumRodjenja = u.DatumRodjenja;

                umrlicaBO.MestoRodjenja = u.MestoRodjenja;

                umrlicaBO.Eparhija = u.Eparhija;

                umrlicaBO.Hram = u.Hram;

                umrlicaBO.TekucaGodina = u.TekucaGodina;

                umrlicaBO.ZanimanjePreminulog = u.ZanimanjePreminulog;

                umrlicaBO.BracnoStanje = u.BracnoStanje;

                umrlicaBO.ImeBracnogPartnera = u.ImeBracnogPartnera;

                umrlicaBO.PrezimeBracnogPartnera = u.PrezimeBracnogPartnera;

                umrlicaBO.ZanimanjeBracnogPartnera = u.ZanimanjeBracnogPartnera;

                umrlicaBO.MestoStanovanjaBracnogPartnera = u.MestoStanovanjaBracnogPartnera;

                umrlicaBO.BrojDece = Convert.ToInt32(u.BrojDece);

                umrlicaBO.PodaciODeci = u.PodaciODeci;

                umrlicaBO.MestoPreminuca = u.MestoPreminuca;

                umrlicaBO.DatumSmrti = u.DatumSmrti;

                umrlicaBO.DatumSahrane = u.DatumSahrane;

                umrlicaBO.MestoIGrobljeSahrane = u.MestoIGrobljeSahrane;

                umrlicaBO.UzrokSmrti = u.UzrokSmrti;

                umrlicaBO.ImeSvestenika = u.ImeSvestenika;

                umrlicaBO.PrezimeSvestenika = u.PrezimeSvestenika;

                umrlicaBO.Primedba = u.Primedba;


                umrlice.Add(umrlicaBO);
            }
            return umrlice;
        }

        public static IEnumerable<Umrlica> GetByIdUm(String ime)
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();

            List<Umrlica> umrlice = new List<Umrlica>();

            foreach (Umrlica u in cr.Umrlicas.Where(t => t.ImePreminulog == ime))
            {
                Umrlica umrlicaBO = new Umrlica();

                umrlicaBO.Dokument = new Dokument()
                {
                    SifraDokumenta = u.Dokument.SifraDokumenta,
                };

                umrlicaBO.SifraUmrlice = u.SifraUmrlice;

                umrlicaBO.ImePreminulog = u.ImePreminulog;

                umrlicaBO.PrezimePreminulog = u.PrezimePreminulog;

                umrlicaBO.Pol = u.Pol;

                umrlicaBO.DatumRodjenja = u.DatumRodjenja;

                umrlicaBO.MestoRodjenja = u.MestoRodjenja;

                umrlicaBO.Eparhija = u.Eparhija;

                umrlicaBO.Hram = u.Hram;

                umrlicaBO.TekucaGodina = u.TekucaGodina;

                umrlicaBO.ZanimanjePreminulog = u.ZanimanjePreminulog;

                umrlicaBO.BracnoStanje = u.BracnoStanje;

                umrlicaBO.ImeBracnogPartnera = u.ImeBracnogPartnera;

                umrlicaBO.PrezimeBracnogPartnera = u.PrezimeBracnogPartnera;

                umrlicaBO.ZanimanjeBracnogPartnera = u.ZanimanjeBracnogPartnera;

                umrlicaBO.MestoStanovanjaBracnogPartnera = u.MestoStanovanjaBracnogPartnera;

                umrlicaBO.BrojDece = Convert.ToInt32(u.BrojDece);

                umrlicaBO.PodaciODeci = u.PodaciODeci;

                umrlicaBO.MestoPreminuca = u.MestoPreminuca;

                umrlicaBO.DatumSmrti = u.DatumSmrti;

                umrlicaBO.DatumSahrane = u.DatumSahrane;

                umrlicaBO.MestoIGrobljeSahrane = u.MestoIGrobljeSahrane;

                umrlicaBO.UzrokSmrti = u.UzrokSmrti;

                umrlicaBO.ImeSvestenika = u.ImeSvestenika;

                umrlicaBO.PrezimeSvestenika = u.PrezimeSvestenika;

                umrlicaBO.Primedba = u.Primedba;


                umrlice.Add(umrlicaBO);
            }
            return umrlice;
        }
    }
}









