

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crkvena_Kancelarija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class VencaniList
    {
        [DisplayName("Шифра документа")]
        [Required(ErrorMessage = "Морате унети шифру 3")]
        public int SifraDokumenta { get; set; }
        [DisplayName("Шифра венчаног листа")]
        [Required(ErrorMessage = "Морате унети шифру венчаног листа")]
        public int SifraVencanogLista { get; set; }
        [DisplayName("Име младожење")]
        [Required(ErrorMessage = "Морате унети име младожење")]
        public string ImeMladozenje { get; set; }
        [DisplayName("Презиме младожење")]
        [Required(ErrorMessage = "Морате унети презиме младожење")]
        public string PrezimeMladozenje { get; set; }
        [DisplayName("Име младе")]
        [Required(ErrorMessage = "Морате унети име младе")]
        public string ImeMlade { get; set; }
        [DisplayName("Презиме младе")]
        [Required(ErrorMessage = "Морате унети презиме младе")]
        public string PrezimeMlade { get; set; }
        [DisplayName("Датум рођења младожење")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Морате унети датум рођења младожење")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumRodjenjaMladozenje { get; set; }
        [DisplayName("Датум рођенња младе")]
        [Required(ErrorMessage = "Морате унети датум рођења младе")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumRodjenjaMlade { get; set; }
        [DisplayName("Место становања младенаца")]
        [Required(ErrorMessage = "Морате унети место становања младенаца")]
        public string MestoStanovanjaMladenaca { get; set; }
        [DisplayName("Вероисповест младожење")]
        [Required(ErrorMessage = "Морате унети вероисповест младожење")]
        public string VeroispovestMladozenje { get; set; }
        [DisplayName("Вероисповест младе")]
        [Required(ErrorMessage = "Морате унети вероисповест младе")]
        public string VeroispovestMlade { get; set; }
        [DisplayName("Народност младожење")]
        [Required(ErrorMessage = "Морате унети народност младожење")]
        public string NarodnostMladozenje { get; set; }
        [DisplayName("Народност младе")]
        [Required(ErrorMessage = "Морате унети народност младе")]
        public string NarodnostMlade { get; set; }
        [DisplayName("Епархија")]
        [Required(ErrorMessage = "Морате унети епархију")]
        public string Eparhija { get; set; }
        [DisplayName("Храм")]
        [Required(ErrorMessage = "Морате унети храм")]
        public string Hram { get; set; }
        [DisplayName("Текућа година")]
        [Required(ErrorMessage = "Морате унети текоћа година")]
        public int TekucaGodina { get; set; }
        [DisplayName("Име оца младожење")]
        [Required(ErrorMessage = "Морате унети име оца младожење")]
        public string ImeOcaMladozenje { get; set; }
        [DisplayName("Презиме младожење")]
        [Required(ErrorMessage = "Морате унети презиме оца младожење")]
        public string PrezimeOcaMladozenje { get; set; }
        [DisplayName("Име мајке младожење")]
        [Required(ErrorMessage = "Морате унети име мајке младожење")]
        public string ImeMajkeMladozenje { get; set; }
        [DisplayName("Презиме мајке младожење")]
        [Required(ErrorMessage = "Морате унети презиме мајке младожење")]
        public string PrezimeMajkeMladozenje { get; set; }
        [DisplayName("Име оца младе")]
        [Required(ErrorMessage = "Морате унети име оца младе")]
        public string ImeOcaMlade { get; set; }
        [DisplayName("Презиме оца Младе")]
        [Required(ErrorMessage = "Морате унети презиме оца младе ")]
        public string PrezimeOcaMlade { get; set; }
        [DisplayName("Име мајке младе")]
        [Required(ErrorMessage = "Морате унети име мајке младе")]
        public string ImeMajkeMlade { get; set; }
        [DisplayName("Презиме мајке младе")]
        [Required(ErrorMessage = "Морате унети презиме мајке младе")]
        public string PrezimeMajkeMlade { get; set; }
        [DisplayName("Брак по реду (Младожења)")]
        [Required(ErrorMessage = "Морате унети брак по реду")]
        public string BrakPoReduMladozenja { get; set; }
        [DisplayName("Брак по реду (Млада)")]
        [Required(ErrorMessage = "Морате унети брак по реду")]
        public string BrakPoReduMlada { get; set; }
        [DisplayName("Испитани и оглашени")]
        [Required(ErrorMessage = "Испитани и оглашени?")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime IspitaniIOglaseni { get; set; }
        [DisplayName("Датум венчања")]
        [Required(ErrorMessage = "Морате унети датум венчања")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DatumVencanja { get; set; }
        [DisplayName("Место венчања")]
        [Required(ErrorMessage = "Морате унети место венчања")]
        public string MestoVencanja { get; set; }
        [DisplayName("Храм венчања")]
        [Required(ErrorMessage = "Морате унети храм венчања")]
        public string HramVencanja { get; set; }
        [DisplayName("Име и презиме кума")]
        [Required(ErrorMessage = "Морате унети име и презиме кума")]
        public string ImeIPrezimeKuma { get; set; }
        [DisplayName("Занимање кума")]
        [Required(ErrorMessage = "Морате унети занимање кума")]
        public string ZanimanjeKuma { get; set; }
        [DisplayName("Место становања кума")]
        [Required(ErrorMessage = "Морате унети место становања кума")]
        public string MestoStanovanjaKuma { get; set; }
        [DisplayName("Име и презиме старог свата")]
        [Required(ErrorMessage = "Морате унети име и презиме старог свата")]
        public string ImeIPrezimeStarogSvata { get; set; }
        [DisplayName("Занимање старог свата")]
        [Required(ErrorMessage = "Морате унети занимање старог свата")]
        public string ZanimanjeStarogSvata { get; set; }
        [DisplayName("Вероисповест старог свата")]
        [Required(ErrorMessage = "Морате унети вероисповест старог свата")]
        public string VeroispovestStarogSvata { get; set; }
        [DisplayName("Место становања старог свата")]
        [Required(ErrorMessage = "Морате унети место становања старог свата")]
        public string MestoStanovanjaStarogSvata { get; set; }
        [DisplayName("Сметње")]
        [DataType(DataType.MultilineText)]
        public string Smetnje { get; set; }
        [DisplayName("Примедба")]
        [DataType(DataType.MultilineText)]
        public string Primedba { get; set; }


        public virtual Dokument Dokument { get; set; }

        public static IEnumerable<VencaniList> GetBySifraVe(int Sifra)
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();
            List<VencaniList> vencaniListovi = new List<VencaniList>();

            foreach (VencaniList v in cr.VencaniLists.Where(t => t.SifraDokumenta == Sifra))
            {
                VencaniList vencaniListBO = new VencaniList();

                vencaniListBO.Dokument = new Dokument()
                {
                    SifraDokumenta = v.Dokument.SifraDokumenta,
                };

                vencaniListBO.SifraVencanogLista = v.SifraVencanogLista;

                vencaniListBO.ImeMladozenje = v.ImeMladozenje;

                vencaniListBO.PrezimeMladozenje = v.PrezimeMladozenje;

                vencaniListBO.ImeMlade = v.ImeMlade;

                vencaniListBO.PrezimeMlade = v.PrezimeMlade;

                vencaniListBO.DatumRodjenjaMladozenje = v.DatumRodjenjaMladozenje;

                vencaniListBO.DatumRodjenjaMlade = v.DatumRodjenjaMlade;

                vencaniListBO.MestoStanovanjaMladenaca = v.MestoStanovanjaMladenaca;

                vencaniListBO.VeroispovestMladozenje = v.VeroispovestMladozenje;

                vencaniListBO.VeroispovestMlade = v.VeroispovestMlade;

                vencaniListBO.NarodnostMladozenje = v.NarodnostMladozenje;

                vencaniListBO.NarodnostMlade = v.NarodnostMlade;

                vencaniListBO.Eparhija = v.Eparhija;

                vencaniListBO.Hram = v.Hram;

                vencaniListBO.TekucaGodina = v.TekucaGodina;

                vencaniListBO.ImeOcaMladozenje = v.ImeOcaMladozenje;

                vencaniListBO.PrezimeOcaMladozenje = v.PrezimeOcaMladozenje;

                vencaniListBO.ImeMajkeMladozenje = v.ImeMajkeMladozenje;

                vencaniListBO.PrezimeMajkeMladozenje = v.PrezimeMajkeMladozenje;

                vencaniListBO.ImeOcaMlade = v.ImeOcaMlade;

                vencaniListBO.PrezimeOcaMlade = v.PrezimeOcaMlade;

                vencaniListBO.ImeMajkeMlade = v.ImeMajkeMlade;

                vencaniListBO.PrezimeMajkeMlade = v.PrezimeMajkeMlade;

                vencaniListBO.BrakPoReduMladozenja = v.BrakPoReduMladozenja;

                vencaniListBO.BrakPoReduMlada = v.BrakPoReduMlada;

                vencaniListBO.IspitaniIOglaseni = v.IspitaniIOglaseni;

                vencaniListBO.DatumVencanja = v.DatumVencanja;

                vencaniListBO.MestoVencanja = v.MestoVencanja;

                vencaniListBO.HramVencanja = v.HramVencanja;

                vencaniListBO.ImeIPrezimeKuma = v.ImeIPrezimeKuma;

                vencaniListBO.ZanimanjeKuma = v.ZanimanjeKuma;

                vencaniListBO.MestoStanovanjaKuma = v.MestoStanovanjaKuma;

                vencaniListBO.ImeIPrezimeStarogSvata = v.ImeIPrezimeStarogSvata;

                vencaniListBO.ZanimanjeStarogSvata = v.ZanimanjeStarogSvata;

                vencaniListBO.VeroispovestStarogSvata = v.VeroispovestStarogSvata;

                vencaniListBO.MestoStanovanjaStarogSvata = v.MestoStanovanjaStarogSvata;

                vencaniListBO.Smetnje = v.Smetnje;

                vencaniListBO.Primedba = v.Primedba;

                vencaniListovi.Add(vencaniListBO);


            }


            return vencaniListovi;
        }

        public static IEnumerable<VencaniList> GetByIdVe(String ime)
        {
            CrkvenaKancelarijaEntities cr = new CrkvenaKancelarijaEntities();
            List<VencaniList> vencaniListovi = new List<VencaniList>();

            foreach (VencaniList v in cr.VencaniLists.Where(p => p.PrezimeMladozenje == ime))
            {
                VencaniList vencaniListBO = new VencaniList();

                vencaniListBO.Dokument = new Dokument()
                {
                    SifraDokumenta = v.Dokument.SifraDokumenta,
                };

                vencaniListBO.SifraVencanogLista = v.SifraVencanogLista;

                vencaniListBO.ImeMladozenje = v.ImeMladozenje;

                vencaniListBO.PrezimeMladozenje = v.PrezimeMladozenje;

                vencaniListBO.ImeMlade = v.ImeMlade;

                vencaniListBO.PrezimeMlade = v.PrezimeMlade;

                vencaniListBO.DatumRodjenjaMladozenje = v.DatumRodjenjaMladozenje;

                vencaniListBO.DatumRodjenjaMlade = v.DatumRodjenjaMlade;

                vencaniListBO.MestoStanovanjaMladenaca = v.MestoStanovanjaMladenaca;

                vencaniListBO.VeroispovestMladozenje = v.VeroispovestMladozenje;

                vencaniListBO.VeroispovestMlade = v.VeroispovestMlade;

                vencaniListBO.NarodnostMladozenje = v.NarodnostMladozenje;

                vencaniListBO.NarodnostMlade = v.NarodnostMlade;

                vencaniListBO.Eparhija = v.Eparhija;

                vencaniListBO.Hram = v.Hram;

                vencaniListBO.TekucaGodina = v.TekucaGodina;

                vencaniListBO.ImeOcaMladozenje = v.ImeOcaMladozenje;

                vencaniListBO.PrezimeOcaMladozenje = v.PrezimeOcaMladozenje;

                vencaniListBO.ImeMajkeMladozenje = v.ImeMajkeMladozenje;

                vencaniListBO.PrezimeMajkeMladozenje = v.PrezimeMajkeMladozenje;

                vencaniListBO.ImeOcaMlade = v.ImeOcaMlade;

                vencaniListBO.PrezimeOcaMlade = v.PrezimeOcaMlade;

                vencaniListBO.ImeMajkeMlade = v.ImeMajkeMlade;

                vencaniListBO.PrezimeMajkeMlade = v.PrezimeMajkeMlade;

                vencaniListBO.BrakPoReduMladozenja = v.BrakPoReduMladozenja;

                vencaniListBO.BrakPoReduMlada = v.BrakPoReduMlada;

                vencaniListBO.IspitaniIOglaseni = v.IspitaniIOglaseni;

                vencaniListBO.DatumVencanja = v.DatumVencanja;

                vencaniListBO.MestoVencanja = v.MestoVencanja;

                vencaniListBO.HramVencanja = v.HramVencanja;

                vencaniListBO.ImeIPrezimeKuma = v.ImeIPrezimeKuma;

                vencaniListBO.ZanimanjeKuma = v.ZanimanjeKuma;

                vencaniListBO.MestoStanovanjaKuma = v.MestoStanovanjaKuma;

                vencaniListBO.ImeIPrezimeStarogSvata = v.ImeIPrezimeStarogSvata;

                vencaniListBO.ZanimanjeStarogSvata = v.ZanimanjeStarogSvata;

                vencaniListBO.VeroispovestStarogSvata = v.VeroispovestStarogSvata;

                vencaniListBO.MestoStanovanjaStarogSvata = v.MestoStanovanjaStarogSvata;

                vencaniListBO.Smetnje = v.Smetnje;

                vencaniListBO.Primedba = v.Primedba;


                vencaniListovi.Add(vencaniListBO);

            }


            return vencaniListovi;
        }
    }
}






